In [7]:
import pandas as pd
import datetime
import numpy as np
import os

In [9]:
df = pd.read_csv("/Users/pilarvasquez/Documents/Repos/AITA-Predictor/reddit_scraper/test.csv")

In [10]:
nan = np.nan

In [11]:
clean_df = df.query("body not in ['[deleted]', '[removed]'] & verdict not in ['TL;DR', 'UPDATE', @nan, 'Talk ENDED']")

In [12]:
clean_df

,title,id,score,upvote_ratio,url,num_comments,body,created,edited,verdict,over_18
1,AITA for refusing to visit my father because o...,rt9vwd,1871,0.97,https://www.reddit.com/r/AmItheAsshole/comment...,226,"Without going into novel length, my father cur...",2021-12-31 23:55:16,False,Not the A-hole,False
3,WIBTA if I told a toddler's mom to have a bett...,rt9v3v,9,0.72,https://www.reddit.com/r/AmItheAsshole/comment...,22,I'm sitting in a local Applebee's and across f...,2021-12-31 23:53:53,False,Everyone Sucks,False
7,AITA for setting social media boundaries?,rt9oqf,37,0.85,https://www.reddit.com/r/AmItheAsshole/comment...,48,"Some background: I’m 19F, I got SEVERELY bulli...",2021-12-31 23:43:31,False,Not the A-hole,False
33,AITA for not answering my spouse’s text while ...,rt8wwk,12,0.78,https://www.reddit.com/r/AmItheAsshole/comment...,21,I (mid twenties female) work in an industrial ...,2021-12-31 23:00:49,1641006051.0,Not the A-hole,False
34,AITA for not caring to see my friends after ha...,rt8wlm,7,0.63,https://www.reddit.com/r/AmItheAsshole/comment...,49,Typing all this out really makes the situation...,2021-12-31 23:00:24,False,No A-holes here,False
...,...,...,...,...,...,...,...,...,...,...,...
49984,AITA for getting pissy with my TA over Discord?,qvu5zs,13,0.94,https://www.reddit.com/r/AmItheAsshole/comment...,19,"For the sake of their and my anonymity, I won'...",2021-11-17 04:48:59,False,Everyone Sucks,False
49989,WIBTA for not sharing estate inheritance,qvtz7m,185,0.95,https://www.reddit.com/r/AmItheAsshole/comment...,47,"Unfortunately, my grandma is severely sick wit...",2021-11-17 04:35:36,1637136111.0,Not the A-hole,False
49993,AITA for getting scammed while being relied on?,qvtsjv,6,0.67,https://www.reddit.com/r/AmItheAsshole/comment...,30,"to sum up a kinda lengthy story, i was walking...",2021-11-17 04:22:26,1637134156.0,Not the A-hole,False
49995,AITA for snapping at my mother?,qvts3m,10,0.81,https://www.reddit.com/r/AmItheAsshole/comment...,18,I took my one year old daughter to see my in l...,2021-11-17 04:21:34,False,Not the A-hole,False
49998,WIBTA if I asked my future MIL to wear a diffe...,qvtqab,7,0.77,https://www.reddit.com/r/AmItheAsshole/comment...,27,(On mobile so sorry for any formatting errors)...,2021-11-17 04:18:02,False,Not the A-hole,False

In [13]:
clean_df.created.tail(10)

49964    2021-11-17 05:48:14
49966    2021-11-17 05:40:59
49967    2021-11-17 05:40:22
49981    2021-11-17 04:54:59
49982    2021-11-17 04:54:34
49984    2021-11-17 04:48:59
49989    2021-11-17 04:35:36
49993    2021-11-17 04:22:26
49995    2021-11-17 04:21:34
49998    2021-11-17 04:18:02
Name: created, dtype: object

In [14]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11555 entries, 1 to 49998
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         11555 non-null  object
 1   id            11555 non-null  object
 2   score         11555 non-null  int64
 3   upvote_ratio  11555 non-null  float64
 4   url           11555 non-null  object
 5   num_comments  11555 non-null  int64
 6   body          11555 non-null  object
 7   created       11555 non-null  object
 8   edited        11555 non-null  object
 9   verdict       11555 non-null  object
 10  over_18       11555 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(7)
memory usage: 1004.3+ KB

In [15]:
clean_df.describe()

              score  upvote_ratio  num_comments
count  11555.000000  11555.000000  11555.000000
mean     588.716313      0.800445    116.757940
std     2309.046615      0.142580    390.437929
min        0.000000      0.100000      0.000000
25%        5.000000      0.710000     15.000000
50%       14.000000      0.830000     27.000000
75%       77.000000      0.920000     57.000000
max    41064.000000      1.000000   8053.000000

In [16]:
clean_df.verdict.value_counts()

Not the A-hole     8580
Asshole            1608
No A-holes here     632
Everyone Sucks      481
Not enough info     251
Open Forum            1
META                  1
Mods Needed!          1
Name: verdict, dtype: int64